first = {
    "programa": ["FUNCTION"],
    "funcao": ["FUNCTION"],
    "funcaoSeq": ["FUNCTION"],
    "listaParams": ["ID"],
    "tipoRetornoFuncao": ["ARROW"],
    "bloco": ["LBRACE"],
    "type_": ["INT", "FLOAT", "CHAR"],
    "listaParams2": ["COMMA"],
    "sequencia": ["LET", "ID", "IF", "WHILE", "PRINT", "PRINTLN", "RETURN"],
    "declaracao": ["LET"],
    "comando": ["ID", "IF", "WHILE", "PRINT", "PRINTLN", "RETURN"],
    "varList": ["ID"],
    "varList2": ["COMMA"],
    "atribuicaoOuChamada": ["ASSINGN", "LPAREN"],
    "comandoIf": ["IF", "LBRACE"],
    "expr": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "listArgs": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "comandoSenao": ["ELSE"],
    "rel": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "exprOpc": ["EQUAL", "NOTEQUAL"],
    "opIgual": ["EQUAL", "NOTEQUAL"],
    "adicao": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "relOpc": ["LT", "LTE", "GT", "GTE"],
    "opRel": ["LT", "LTE", "GT", "GTE"],
    "termo": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "adicaoOpc": ["PLUS", "MINUS"],
    "opAdicao": ["PLUS", "MINUS"],
    "fator": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "termoOpc": ["MULT", "DIV"],
    "opMult": ["MULT", "DIV"],
    "chamadaFuncao": ["LPAREN"],
    "listArgs2": ["COMMA"]
}

follow = {
    "programa": [],
    "funcao": ["FUNCTION"],
    "funcaoSeq": [],
    "listaParams": ["RPAREN"],
    "tipoRetornoFuncao": ["LBRACE"],
    "bloco": ["FUNCTION", "ID", "LBRACE", "RBRACE", "LET", "WHILE", "PRINT", "PRINTLN", "RETURN", "IF", "ELSE"],
    "type_": ["RPAREN", "COMMA", "LBRACE", "SEMICOLON"],
    "listaParams2": ["RPAREN"],
    "sequencia": ["RBRACE"],
    "declaracao": ["ID", "LBRACE", "RBRACE", "LET", "WHILE", "PRINT", "PRINTLN", "RETURN", "IF"],
    "comando": ["ID", "LBRACE", "RBRACE", "LET", "WHILE", "PRINT", "PRINTLN", "RETURN", "IF"],
    "varList": ["COLON"],
    "varList2": ["COLON"],
    "atribuicaoOuChamada": ["ID", "LBRACE", "RBRACE", "LET", "WHILE", "PRINT", "PRINTLN", "RETURN", "IF"],
    "comandoIf": ["ID", "LBRACE", "RBRACE", "LET", "WHILE", "PRINT", "PRINTLN", "RETURN", "IF"],
    "expr": ["RPAREN", "LBRACE", "SEMICOLON"],
    "listArgs": ["RPAREN"],
    "comandoSenao": ["ID", "LBRACE", "RBRACE", "LET", "WHILE", "PRINT", "PRINTLN", "RETURN", "IF"],
    "rel": ["RPAREN", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL"],
    "exprOpc": ["RPAREN", "LBRACE", "SEMICOLON"],
    "opIgual": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "adicao": ["RPAREN", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL", "LT", "LTE", "GT", "GTE"],
    "relOpc": ["RPAREN", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL"],
    "opRel": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "termo": ["RPAREN", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL", "LT", "LTE", "GT", "GTE", "PLUS", "MINUS"],
    "adicaoOpc": ["RPAREN", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL", "LT", "LTE", "GT", "GTE"],
    "opAdicao": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "fator": ["RPAREN", "COMMA", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL", "LT", "LTE", "GT", "GTE", "PLUS", "MINUS", "MULT", "DIV"],
    "termoOpc": ["RPAREN", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL", "LT", "LTE", "GT", "GTE", "PLUS", "MINUS"],
    "opMult": ["ID", "INT_CONST", "FLOAT_CONST", "CHAR_LITERAL", "LPAREN"],
    "chamadaFuncao": ["RPAREN", "COMMA", "LBRACE", "SEMICOLON", "EQUAL", "NOTEQUAL", "LT", "LTE", "GT", "GTE", "PLUS", "MINUS", "MULT", "DIV"],
    "listArgs2": ["RPAREN"]
}
